export const GRADES_PAYLOAD = {
  joinIdenticalLines: false,
  searchResultDefinition: {
    modelName: "Registration",
    api: "registrations",
    lang: "fr",
    queryTitle: {
      en: "Display Favorite - Ratings and Reviews (APP)",
      fr: "Favori d'affichage - Évaluations et notes (APP)",
    },
    filtersCustom: {
      id: null,
      customAttributes: null,
      externalCode: null,
      objectSharingDomains: null,
      queryFilter: null,
    },
    columns: [
      {
        guid: "bb965b1c-2a04-4fca-bee7-d7875ab484c8",
        visible: true,
        path: "Registration",
        api: "registrations",
        field: "obligation",
        label: {
          en: "Pedagogical component",
          fr: "Composant pédagogique",
        },
        defaultLabel: {
          en: "Pedagogical component",
          fr: "Composant pédagogique",
        },
        modelName: "Registration",
        modelDestName: "Obligation",
        isReverted: null,
        type: "primaryforeignkey",
        order: null,
        orderGlobal: null,
        excluded: false,
        isDisplayedInSelect: true,
        multilingual: false,
        isCustom: false,
        isParameterized: null,
        children: [
          {
            guid: "ca3f754b-7e08-44e2-a533-c0c0dcc60843",
            visible: true,
            path: "Registration-obligation",
            api: "obligations",
            field: "code",
            label: {
              en: "Pedagogical component",
              fr: "Composant pédagogique",
            },
            defaultLabel: {
              en: "Code",
              fr: "Code",
            },
            modelName: "Obligation",
            modelDestName: null,
            isReverted: null,
            type: "code",
            order: 0,
            orderGlobal: 0,
            excluded: null,
            isDisplayedInSelect: false,
            multilingual: false,
            isCustom: false,
            isParameterized: null,
            children: null,
          },
          {
            guid: "693bbcbe-0846-41ca-8f68-17c1132aafb5",
            visible: true,
            path: "Registration-obligation",
            api: "obligations",
            field: "exam",
            label: {
              en: "Pedagogical component.Exam",
              fr: "Composant pédagogique.Épreuve",
            },
            defaultLabel: {
              en: "Exam",
              fr: "Épreuve",
            },
            modelName: "Obligation",
            modelDestName: "Exam",
            isReverted: null,
            type: "primaryforeignkey",
            order: null,
            orderGlobal: null,
            excluded: false,
            isDisplayedInSelect: true,
            multilingual: false,
            isCustom: false,
            isParameterized: null,
            children: [
              {
                guid: "be4fb949-04dd-4d64-b9c5-da6066bdef9d",
                visible: true,
                path: "Registration-obligation-exam",
                api: "exams",
                field: "code",
                label: {
                  en: "Exam.Code",
                  fr: "Épreuve",
                },
                defaultLabel: {
                  en: "Code",
                  fr: "Code",
                },
                modelName: "Exam",
                modelDestName: null,
                isReverted: null,
                type: "code",
                order: 1,
                orderGlobal: 1,
                excluded: null,
                isDisplayedInSelect: true,
                multilingual: false,
                isCustom: false,
                isParameterized: null,
                children: null,
              },
              {
                guid: "e7843240-81c0-4d10-b125-56a991ee6b1a",
                visible: true,
                path: "Registration-obligation-exam",
                api: "exams",
                field: "examType",
                label: {
                  en: "Exam.Exam type",
                  fr: "Épreuve.Type d'examen",
                },
                defaultLabel: {
                  en: "Exam type",
                  fr: "Type d'examen",
                },
                modelName: "Exam",
                modelDestName: "ExamType",
                isReverted: null,
                type: "foreignkey",
                order: null,
                orderGlobal: null,
                excluded: false,
                isDisplayedInSelect: true,
                multilingual: false,
                isCustom: false,
                isParameterized: null,
                children: [
                  {
                    guid: "f9f90058-01b9-4253-b29d-cd6cc4a6dc61",
                    visible: true,
                    path: "Registration-obligation-exam-examType",
                    api: "examTypes",
                    field: "code",
                    label: {
                      en: "Exam type",
                      fr: "Type d'examen",
                    },
                    defaultLabel: {
                      en: "Code",
                      fr: "Code",
                    },
                    modelName: "ExamType",
                    modelDestName: null,
                    isReverted: null,
                    type: "code",
                    order: 2,
                    orderGlobal: 2,
                    excluded: null,
                    isDisplayedInSelect: true,
                    multilingual: false,
                    isCustom: false,
                    isParameterized: null,
                    children: null,
                  },
                ],
              },
              {
                guid: "c7bf8cdb-b98b-4872-936d-a87cb7b2eaa8",
                visible: true,
                path: "Registration-obligation-exam",
                api: "exams",
                field: "intervention",
                label: {
                  en: "Exam.Intervention",
                  fr: "Épreuve.Intervention",
                },
                defaultLabel: {
                  en: "Intervention",
                  fr: "Intervention",
                },
                modelName: "Exam",
                modelDestName: "Intervention",
                isReverted: null,
                type: "foreignkey",
                order: null,
                orderGlobal: null,
                excluded: false,
                isDisplayedInSelect: true,
                multilingual: false,
                isCustom: false,
                isParameterized: null,
                children: [
                  {
                    guid: "88124acc-a8ff-43ca-8c3d-a7c220852e83",
                    visible: false,
                    path: "Registration-obligation-exam-intervention",
                    api: "interventions",
                    field: "startDateTime",
                    label: {
                      en: "Date",
                      fr: "Date",
                    },
                    defaultLabel: {
                      en: "Start",
                      fr: "Début",
                    },
                    modelName: "Intervention",
                    modelDestName: null,
                    isReverted: null,
                    type: "timestamptz",
                    order: 7,
                    orderGlobal: 3,
                    excluded: null,
                    isDisplayedInSelect: true,
                    multilingual: false,
                    isCustom: false,
                    isParameterized: null,
                    children: null,
                  },
                ],
              },
              {
                guid: "df564842-1b1a-473a-810e-fdf884fba553",
                visible: false,
                path: "Registration-obligation-exam",
                api: "exams",
                field: "diffusionDate",
                label: {
                  en: "Exam.Diffusion date",
                  fr: "Épreuve.Date de diffusion",
                },
                defaultLabel: {
                  en: "Diffusion date",
                  fr: "Date de diffusion",
                },
                modelName: "Exam",
                modelDestName: null,
                isReverted: null,
                type: "date",
                order: 9,
                orderGlobal: 9,
                excluded: null,
                isDisplayedInSelect: false,
                multilingual: false,
                isCustom: false,
                isParameterized: null,
                children: null,
              },
            ],
          },
          {
            guid: "6cb41bf2-2a65-45a1-987d-8dd721a07303",
            visible: true,
            path: "Registration-obligation",
            api: "obligations",
            field: "alphaScale",
            label: {
              en: "Pedagogical component.Alphanumeric scale",
              fr: "Composant pédagogique.Grille alphanumérique",
            },
            defaultLabel: {
              en: "Alphanumeric scale",
              fr: "Grille alphanumérique",
            },
            modelName: "Obligation",
            modelDestName: "AlphaScale",
            isReverted: null,
            type: "foreignkey",
            order: null,
            orderGlobal: null,
            excluded: false,
            isDisplayedInSelect: true,
            multilingual: false,
            isCustom: false,
            isParameterized: null,
            children: [
              {
                guid: "723620bb-8653-490c-9781-211b29875ac4",
                visible: false,
                path: "Registration-obligation-alphaScale",
                api: "alphaScales",
                field: "code",
                label: {
                  en: "Alphanumeric scale.Code",
                  fr: "Grille alphanumérique.Code",
                },
                defaultLabel: {
                  en: "Code",
                  fr: "Code",
                },
                modelName: "AlphaScale",
                modelDestName: null,
                isReverted: null,
                type: "code",
                order: 11,
                orderGlobal: 7,
                excluded: null,
                isDisplayedInSelect: true,
                multilingual: false,
                isCustom: false,
                isParameterized: null,
                children: null,
              },
            ],
          },
        ],
      },
      {
        guid: "2938be38-6fd0-40ba-b40f-7c9fe8401e7a",
        visible: false,
        path: "Registration",
        api: "registrations",
        field: "mark",
        label: {
          en: "Mark.Initial",
          fr: "Note.Initiale",
        },
        defaultLabel: {
          en: "Mark",
          fr: "Note",
        },
        modelName: "Registration",
        modelDestName: null,
        isReverted: null,
        type: "numeric",
        order: 8,
        orderGlobal: 5,
        excluded: null,
        isDisplayedInSelect: false,
        multilingual: false,
        isCustom: false,
        isParameterized: null,
        children: null,
      },
      {
        guid: "e6c57faa-56d3-43b2-8f57-dad1bb314d7a",
        visible: true,
        path: "Registration",
        api: "registrations",
        field: "person",
        label: {
          en: "Person",
          fr: "Individu",
        },
        defaultLabel: {
          en: "Person",
          fr: "Individu",
        },
        modelName: "Registration",
        modelDestName: "Person",
        isReverted: null,
        type: "primaryforeignkey",
        order: null,
        orderGlobal: null,
        excluded: false,
        isDisplayedInSelect: true,
        multilingual: false,
        isCustom: false,
        isParameterized: null,
        children: [
          {
            guid: "4390e948-add1-4fe0-9a39-a21e079f563b",
            visible: false,
            path: "Registration-person",
            api: "persons",
            field: "id",
            label: {
              en: "Person.ID",
              fr: "Individu.ID",
            },
            defaultLabel: {
              en: "ID",
              fr: "ID",
            },
            modelName: "Person",
            modelDestName: null,
            isReverted: null,
            type: "integer",
            order: 10,
            orderGlobal: 8,
            excluded: null,
            isDisplayedInSelect: false,
            multilingual: false,
            isCustom: false,
            isParameterized: true,
            children: null,
          },
        ],
      },
      {
        guid: "a27c9d37-a32e-41bc-9918-fbcdbd55ef67",
        visible: false,
        path: "Registration",
        api: "registrations",
        field: "alphaMark",
        label: {
          en: "Alpha mark",
          fr: "Note alphanumérique",
        },
        defaultLabel: {
          en: "Alpha mark",
          fr: "Note alphanumérique",
        },
        modelName: "Registration",
        modelDestName: null,
        isReverted: null,
        type: "string",
        order: 12,
        orderGlobal: 6,
        excluded: null,
        isDisplayedInSelect: false,
        multilingual: false,
        isCustom: false,
        isParameterized: null,
        children: null,
      },
      {
        guid: "fcddbeda-0fb4-48b1-9ac9-bbef5612180d",
        visible: true,
        path: null,
        api: null,
        field: "calculatedField",
        label: {
          en: "Mark",
          fr: "Note",
        },
        defaultLabel: {
          en: "Calculated field 1",
          fr: "Champ calculé 1",
        },
        modelName: null,
        modelDestName: null,
        isReverted: null,
        calculated: true,
        type: "string",
        order: 3,
        orderGlobal: 4,
        excluded: null,
        operations: [
          {
            operation: "cfoCaseIfNull",
            parameters: [
              {
                function: "cffRawString",
                column: "6f878063-7f57-4623-8b1e-9cba7bad3cd7",
                value: null,
                index: 0,
              },
              {
                function: "cffRawStringForNumeric",
                column: "2938be38-6fd0-40ba-b40f-7c9fe8401e7a",
                value: null,
                index: 1,
              },
            ],
          },
        ],
        isDisplayedInSelect: true,
        multilingual: null,
        isCustom: null,
        isParameterized: null,
        children: null,
      },
      {
        guid: "5bd0f601-1f9e-4fff-8987-8873d81e466d",
        visible: false,
        path: null,
        api: null,
        field: "calculatedField",
        label: {
          en: "Calculated field 2",
          fr: "VA.ToutesLettres",
        },
        defaultLabel: {
          en: "Calculated field 2",
          fr: "Champ calculé 2",
        },
        modelName: null,
        modelDestName: null,
        isReverted: null,
        calculated: true,
        type: "string",
        order: 4,
        orderGlobal: null,
        excluded: null,
        operations: [
          {
            operation: "cfoEqual",
            parameters: [
              {
                function: "cffRawString",
                column: "a27c9d37-a32e-41bc-9918-fbcdbd55ef67",
                value: null,
                index: 0,
              },
              {
                function: "cffRawString",
                column: null,
                value: "VA",
                index: 1,
              },
            ],
          },
          {
            operation: "cfoIfTrueThenString",
            parameters: [
              {
                function: "cffRaw",
                column: null,
                value: null,
                index: 0,
                previousOperation: true,
              },
              {
                function: "cffRawString",
                column: null,
                value: "Validé",
                index: 1,
              },
            ],
          },
        ],
        isDisplayedInSelect: true,
        multilingual: null,
        isCustom: null,
        isParameterized: null,
        children: null,
      },
      {
        guid: "383720b2-9bf4-4fdc-8fc3-5e0dd7bc3fa3",
        visible: false,
        path: null,
        api: null,
        field: "calculatedField",
        label: {
          en: "Calculated field 3",
          fr: "NV.ToutesLettres",
        },
        defaultLabel: {
          en: "Calculated field 3",
          fr: "Champ calculé 3",
        },
        modelName: null,
        modelDestName: null,
        isReverted: null,
        calculated: true,
        type: "string",
        order: 5,
        orderGlobal: null,
        excluded: null,
        operations: [
          {
            operation: "cfoEqual",
            parameters: [
              {
                function: "cffRawString",
                column: "a27c9d37-a32e-41bc-9918-fbcdbd55ef67",
                value: null,
                index: 0,
              },
              {
                function: "cffRawString",
                column: null,
                value: "NV",
                index: 1,
              },
            ],
          },
          {
            operation: "cfoIfTrueThenString",
            parameters: [
              {
                function: "cffRaw",
                column: null,
                value: null,
                index: 0,
                previousOperation: true,
              },
              {
                function: "cffRawString",
                column: null,
                value: "Non validé",
                index: 1,
              },
            ],
          },
        ],
        isDisplayedInSelect: true,
        multilingual: null,
        isCustom: null,
        isParameterized: null,
        children: null,
      },
      {
        guid: "6f878063-7f57-4623-8b1e-9cba7bad3cd7",
        visible: false,
        path: null,
        api: null,
        field: "calculatedField",
        label: {
          en: "Calculated field 4",
          fr: "Concat.VA.NV.ToutesLettres",
        },
        defaultLabel: {
          en: "Calculated field 4",
          fr: "Champ calculé 4",
        },
        modelName: null,
        modelDestName: null,
        isReverted: null,
        calculated: true,
        type: "string",
        order: 6,
        orderGlobal: null,
        excluded: null,
        operations: [
          {
            operation: "cfoConcat",
            parameters: [
              {
                function: "cffRawString",
                column: "5bd0f601-1f9e-4fff-8987-8873d81e466d",
                value: null,
                index: 0,
              },
              {
                function: "cffRawString",
                column: "383720b2-9bf4-4fdc-8fc3-5e0dd7bc3fa3",
                value: null,
                index: 1,
              },
            ],
          },
        ],
        isDisplayedInSelect: true,
        multilingual: null,
        isCustom: null,
        isParameterized: null,
        children: null,
      },
    ],
    filters: {
      booleanOperator: "and",
      conditions: [
        {
          guid: "fcddbeda-0fb4-48b1-9ac9-bbef5612180d",
          visible: null,
          path: null,
          api: null,
          field: "calculatedField",
          label: null,
          defaultLabel: null,
          modelName: null,
          modelDestName: null,
          isReverted: null,
          type: null,
          order: null,
          orderGlobal: null,
          excluded: null,
          operator: "notEqual",
          value: [],
          isParameterized: false,
          ignoreParameterized: false,
        },
        {
          guid: "df564842-1b1a-473a-810e-fdf884fba553",
          visible: null,
          path: "Registration-obligation-exam",
          api: "exams",
          field: "diffusionDate",
          label: null,
          defaultLabel: null,
          modelName: "Exam",
          modelDestName: null,
          isReverted: null,
          type: null,
          order: null,
          orderGlobal: null,
          excluded: null,
          operator: "less",
          value: ["today"],
          isParameterized: null,
          ignoreParameterized: false,
        },
      ],
    },
    hiddenFilters: null,
    subQueries: [],
    joinSameFields: null,
    excluded: true,
  },
  searchResultGlobal: {
    columns: [],
    filters: null,
    hiddenFilters: {
      booleanOperator: null,
      conditions: [],
    },
    sorts: [
      {
        guid: "ca3f754b-7e08-44e2-a533-c0c0dcc60843",
        visible: null,
        path: "Registration-obligation",
        api: "obligations",
        field: "code",
        label: null,
        defaultLabel: null,
        modelName: "Obligation",
        modelDestName: null,
        isReverted: null,
        type: null,
        order: null,
        orderGlobal: null,
        excluded: null,
        desc: false,
      },
    ],
    dataviz: null,
    timezone: "Europe/Paris",
  },
  queryId: 945,
};
