export const GRADES_PAYLOAD = {
  joinIdenticalLines: null,
  searchResultDefinition: {
    modelName: "Registration",
    api: "registrations",
    lang: null,
    queryTitle: {
      en: "Default Query for Registration",
      fr: "Favori par défaut de Inscription",
    },
    filtersCustom: null,
    columns: [
      {
        guid: "577b3195-2bd0-47e0-b6e5-4f40f2fef767",
        visible: false,
        path: "Registration",
        api: "registrations",
        field: "id",
        label: {
          en: "ID",
          fr: "ID",
        },
        defaultLabel: {
          en: "ID",
          fr: "ID",
        },
        modelName: "Registration",
        modelDestName: null,
        isReverted: null,
        type: "integer",
        order: 1,
        orderGlobal: 1,
        excluded: null,
        isDisplayedInSelect: false,
        multilingual: false,
        isCustom: false,
        isParameterized: null,
        children: null,
      },
      {
        guid: "1cd095ee-ae46-45ef-b855-331004bb9d54",
        visible: true,
        path: "Registration",
        api: "registrations",
        field: "registrationCaption",
        label: {
          en: "Registration label",
          fr: "Libellé de l''inscription",
        },
        defaultLabel: {
          en: "Registration label",
          fr: "Libellé de l''inscription",
        },
        modelName: "Registration",
        modelDestName: null,
        isReverted: null,
        type: "mlstring",
        order: 2,
        orderGlobal: 2,
        excluded: null,
        isDisplayedInSelect: false,
        multilingual: true,
        isCustom: false,
        isParameterized: null,
        children: null,
      },
      {
        guid: "bd9de356-d748-4cb1-807a-4c919d146903",
        visible: true,
        path: "Registration",
        api: "registrations",
        field: "studentId",
        label: {
          en: "Student",
          fr: "Etudiant",
        },
        defaultLabel: {
          en: "Student",
          fr: "Etudiant",
        },
        modelName: "Registration",
        modelDestName: "Student",
        isReverted: null,
        type: "foreignkey",
        order: null,
        orderGlobal: null,
        excluded: null,
        isDisplayedInSelect: true,
        multilingual: false,
        isCustom: false,
        isParameterized: null,
        children: [
          {
            guid: "c0da455a-df34-45d6-848e-2895690b63bd",
            visible: false,
            path: "Registration-student",
            api: "students",
            field: "id",
            label: {
              en: "Student.ID",
              fr: "Etudiant.ID",
            },
            defaultLabel: {
              en: "ID",
              fr: "ID",
            },
            modelName: "Student",
            modelDestName: null,
            isReverted: null,
            type: "integer",
            order: 3,
            orderGlobal: 3,
            excluded: null,
            isDisplayedInSelect: true,
            multilingual: false,
            isCustom: false,
            isParameterized: null,
            children: null,
          },
          {
            guid: "d677611e-b49b-4395-812e-a50d24f0c406",
            visible: true,
            path: "Registration-student",
            api: "students",
            field: "fullName",
            label: {
              en: "Student.Full Name",
              fr: "Student.Nom complet",
            },
            defaultLabel: {
              en: "Full Name",
              fr: "Nom complet",
            },
            modelName: "Student",
            modelDestName: null,
            isReverted: null,
            type: "string",
            order: 5,
            orderGlobal: 5,
            excluded: null,
            isDisplayedInSelect: true,
            multilingual: false,
            isCustom: false,
            isParameterized: null,
            children: null,
          },
        ],
      },
      {
        guid: "c5cf7e88-6625-460d-85fa-71d50c765c71",
        visible: true,
        path: "Registration",
        api: "registrations",
        field: "grade",
        label: {
          en: "Grade",
          fr: "Note",
        },
        defaultLabel: {
          en: "Grade",
          fr: "Note",
        },
        modelName: "Registration",
        modelDestName: null,
        isReverted: null,
        type: "numeric",
        order: 6,
        orderGlobal: 6,
        excluded: null,
        isDisplayedInSelect: true,
        multilingual: false,
        isCustom: false,
        isParameterized: null,
        children: null,
      },
      {
        guid: "f626db73-c827-4400-9943-7f212261edce",
        visible: true,
        path: "Registration",
        api: "registrations",
        field: "item",
        label: {
          en: "Item",
          fr: "Elément",
        },
        defaultLabel: {
          en: "Item",
          fr: "Elément",
        },
        modelName: "Registration",
        modelDestName: "Item",
        isReverted: null,
        type: "foreignkey",
        order: null,
        orderGlobal: null,
        excluded: null,
        isDisplayedInSelect: true,
        multilingual: false,
        isCustom: false,
        isParameterized: null,
        children: [
          {
            guid: "ce0435b8-d2ea-4a46-8dc6-b9968417cd9c",
            visible: false,
            path: "Registration-item",
            api: "items",
            field: "id",
            label: {
              en: "Item.ID",
              fr: "Elément.ID",
            },
            defaultLabel: {
              en: "ID",
              fr: "ID",
            },
            modelName: "Item",
            modelDestName: null,
            isReverted: null,
            type: "integer",
            order: 8,
            orderGlobal: 8,
            excluded: null,
            isDisplayedInSelect: true,
            multilingual: false,
            isCustom: false,
            isParameterized: null,
            children: null,
          },
          {
            guid: "d603a1fc-2244-41d9-813c-ccbb4930114b",
            visible: false,
            path: "Registration-item",
            api: "items",
            field: "code",
            label: {
              en: "Item.Code",
              fr: "Elément.Code",
            },
            defaultLabel: {
              en: "Code",
              fr: "Code",
            },
            modelName: "Item",
            modelDestName: null,
            isReverted: null,
            type: "code",
            order: 9,
            orderGlobal: 9,
            excluded: null,
            isDisplayedInSelect: true,
            multilingual: false,
            isCustom: false,
            isParameterized: null,
            children: null,
          },
          {
            guid: "7132800d-f217-4fdc-9d10-86b24054a7c1",
            visible: true,
            path: "Registration-item",
            api: "items",
            field: "caption",
            label: {
              en: "Item.Caption",
              fr: "Item.Libellé",
            },
            defaultLabel: {
              en: "Caption",
              fr: "Libellé",
            },
            modelName: "Item",
            modelDestName: null,
            isReverted: null,
            type: "mlstring",
            order: 12,
            orderGlobal: 12,
            excluded: null,
            isDisplayedInSelect: true,
            multilingual: true,
            isCustom: false,
            isParameterized: null,
            children: null,
          },
          {
            guid: "bd92534f-0131-4a12-8700-111c1e57c6b7",
            visible: true,
            path: "Registration-item",
            api: "items",
            field: "period",
            label: {
              en: "Period",
              fr: "Période",
            },
            defaultLabel: {
              en: "Period",
              fr: "Période",
            },
            modelName: "Item",
            modelDestName: "Period",
            isReverted: null,
            type: "foreignkey",
            order: null,
            orderGlobal: null,
            excluded: null,
            isDisplayedInSelect: true,
            multilingual: false,
            isCustom: false,
            isParameterized: null,
            children: [
              {
                guid: "4c042fe9-c967-4221-a53b-e987c9f86326",
                visible: false,
                path: "Registration-item-period",
                api: "periods",
                field: "id",
                label: {
                  en: "Period.ID",
                  fr: "Période.ID",
                },
                defaultLabel: {
                  en: "ID",
                  fr: "ID",
                },
                modelName: "Period",
                modelDestName: null,
                isReverted: null,
                type: "integer",
                order: 14,
                orderGlobal: 14,
                excluded: null,
                isDisplayedInSelect: true,
                multilingual: false,
                isCustom: false,
                isParameterized: null,
                children: null,
              },
              {
                guid: "060a876a-5481-432d-8692-0b70a7ce2435",
                visible: false,
                path: "Registration-item-period",
                api: "periods",
                field: "code",
                label: {
                  en: "Period.Code",
                  fr: "Période.Code",
                },
                defaultLabel: {
                  en: "Code",
                  fr: "Code",
                },
                modelName: "Period",
                modelDestName: null,
                isReverted: null,
                type: "code",
                order: 15,
                orderGlobal: 15,
                excluded: null,
                isDisplayedInSelect: true,
                multilingual: false,
                isCustom: false,
                isParameterized: null,
                children: null,
              },
              {
                guid: "da14ab77-d07f-4428-ba78-2d832c3008ea",
                visible: true,
                path: "Registration-item-period",
                api: "periods",
                field: "caption",
                label: {
                  en: "Period.Caption",
                  fr: "Period.Libellé",
                },
                defaultLabel: {
                  en: "Caption",
                  fr: "Libellé",
                },
                modelName: "Period",
                modelDestName: null,
                isReverted: null,
                type: "mlstring",
                order: 16,
                orderGlobal: 16,
                excluded: null,
                isDisplayedInSelect: true,
                multilingual: true,
                isCustom: false,
                isParameterized: null,
                children: null,
              },
            ],
          },
          {
            guid: "3b292eaf-2525-455a-bd55-aed282e850b5",
            visible: true,
            path: "Registration-item",
            api: "items",
            field: "itemType",
            label: {
              en: "Item Type",
              fr: "Type d''élément",
            },
            defaultLabel: {
              en: "Item Type",
              fr: "Type d''élément",
            },
            modelName: "Item",
            modelDestName: "ItemType",
            isReverted: null,
            type: "foreignkey",
            order: null,
            orderGlobal: null,
            excluded: null,
            isDisplayedInSelect: true,
            multilingual: false,
            isCustom: false,
            isParameterized: null,
            children: [
              {
                guid: "f7ab2528-dc06-4927-a065-f90372138927",
                visible: false,
                path: "Registration-item-itemType",
                api: "itemTypes",
                field: "id",
                label: {
                  en: "Item Type.ID",
                  fr: "Type d''élément.ID",
                },
                defaultLabel: {
                  en: "ID",
                  fr: "ID",
                },
                modelName: "ItemType",
                modelDestName: null,
                isReverted: null,
                type: "integer",
                order: 18,
                orderGlobal: 18,
                excluded: null,
                isDisplayedInSelect: true,
                multilingual: false,
                isCustom: false,
                isParameterized: null,
                children: null,
              },
              {
                guid: "4c431aa5-6d0a-4228-854e-e1bb1b2e84d4",
                visible: false,
                path: "Registration-item-itemType",
                api: "itemTypes",
                field: "code",
                label: {
                  en: "Item Type.Code",
                  fr: "Type d''élément.Code",
                },
                defaultLabel: {
                  en: "Code",
                  fr: "Code",
                },
                modelName: "ItemType",
                modelDestName: null,
                isReverted: null,
                type: "code",
                order: 19,
                orderGlobal: 19,
                excluded: null,
                isDisplayedInSelect: true,
                multilingual: false,
                isCustom: false,
                isParameterized: null,
                children: null,
              },
              {
                guid: "669926d7-83eb-410a-afe1-e2dd6d8fe375",
                visible: true,
                path: "Registration-item-itemType",
                api: "itemTypes",
                field: "caption",
                label: {
                  en: "ItemType.Caption",
                  fr: "ItemType.Libellé",
                },
                defaultLabel: {
                  en: "Caption",
                  fr: "Libellé",
                },
                modelName: "ItemType",
                modelDestName: null,
                isReverted: null,
                type: "mlstring",
                order: 20,
                orderGlobal: 20,
                excluded: null,
                isDisplayedInSelect: true,
                multilingual: true,
                isCustom: false,
                isParameterized: null,
                children: null,
              },
            ],
          },
        ],
      },
    ],
    filters: null,
    hiddenFilters: null,
    subQueries: null,
    joinSameFields: null,
    excluded: true,
  },
  searchResultGlobal: {
    columns: null,
    filters: null,
    hiddenFilters: null,
    sorts: [
      {
        guid: "577b3195-2bd0-47e0-b6e5-4f40f2fef767",
        visible: null,
        path: "Registration",
        api: "registrations",
        field: "id",
        label: null,
        defaultLabel: null,
        modelName: "Registration",
        modelDestName: null,
        isReverted: null,
        type: null,
        order: null,
        orderGlobal: null,
        excluded: null,
        desc: true,
      },
    ],
    dataviz: null,
    timezone: null,
  },
};
